server:
    port: 8082

swagger:
    title: List Movies
    description: API para lista de filmes

springdoc:
    packagesToScan: com.observability.com.rentmovie.controller

spring:
    data:
        mongodb:
            uri: ${MONGO_DB:mongodb://localhost:27018/rent-movie}
    application:
        name: rent-movie
        movie:
            url: ${URL_MOVIE_CATALOG:http://localhost:8081/movie}

logging:
    level:
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
    health:
        diskspace:
            enabled: false
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: prometheus,health
            base-path: '/'
            path-mapping:
                prometheus: 'metrics'