version: "3.8"
services:
    mongo:
        container_name: mongo
        image: mongo:4.2
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: movie-catalog
        volumes:
            - ./mongodb:/data/db
        networks:
            - observability
networks:
    observability:
        external: true